/*==============================================================================
  Step W0 - Setup and extract RLMS data

  Project : Welfare Cost of Labor Informality
  Data    : RLMS-HSE 1994-2023 (combined long-format DTA files)
  Author  : A. Malkova

  Purpose : (1) Define global macros for all project paths
            (2) Write a reusable welfare_globals.do helper
            (3) Verify that the combined DTA files exist
            (4) Quick describe of each file
            (5) Print round-to-year mapping

  Notes   : RAR archives have already been extracted.
            The data ship as two combined long-format files:
              - RLMS_IND_1994_2023_eng_dta.dta  (~10 GB, person-year)
              - RLMS_HH_1994_2023_eng_dta.dta   (~2.5 GB, household-year)
            Both files are ALREADY IN LONG FORMAT:
              - IND: one obs per person-year  (idind x id_w)
              - HH:  one obs per household-year (id_h x id_w)
            No appending or reshaping is needed.
==============================================================================*/

clear all
set more off
capture set maxvar 32767
set matsize 11000
version 16

* ============================================================================ *
*   1.  GLOBAL PATH MACROS
* ============================================================================ *

global base     "/Users/amalkova/Library/CloudStorage/OneDrive-FloridaInstituteofTechnology/Credit market (1)"
global welfare  "${base}/Welfare analysis"
global dodir    "${welfare}/Do files"
global dofiles  "${welfare}/Do files"
global data     "${welfare}/Data"
global results  "${welfare}/Results"
global tables   "${welfare}/Tables"
global figures  "${welfare}/Figures"
global logdir   "${welfare}/Logs"
global crdata   "${base}/Comparative Economics"

* Combined DTA files are already extracted into Data/HH and Data/IND
global ind_combined  "${data}/IND/RLMS_IND_1994_2023_eng_dta.dta"
global hh_combined   "${data}/HH/RLMS_HH_1994_2023_eng_dta.dta"

* ============================================================================ *
*   2.  CREATE DIRECTORY STRUCTURE (if not already present)
* ============================================================================ *

foreach d in welfare dodir data results tables figures logdir {
    capture mkdir "${`d'}"
}

* ============================================================================ *
*   3.  START LOG
* ============================================================================ *

capture log close _all
local today : display %tdCYND date(c(current_date), "DMY")
local today = trim("`today'")
log using "${logdir}/W0_setup_`today'.log", replace text name(w0)

display as result _n "===== Step W0 - Setup and extract RLMS data =====" _n
display as result "Run date : `c(current_date)'  `c(current_time)'"
display as result "Stata    : `c(stata_version)' (`c(flavor)')"
display as result "Machine  : `c(machine_type)', `c(os)'"
display as result "Base path: ${base}"

* ============================================================================ *
*   4.  WRITE welfare_globals.do (reusable helper sourced by later steps)
* ============================================================================ *

capture file close _globals
file open _globals using "${dodir}/welfare_globals.do", write replace

file write _globals ///
    `"/*=============================================="' _n ///
    `"  Welfare Analysis -- Global macros"' _n ///
    `"  Auto-generated by Step W0"' _n ///
    `"  Called by all Step W*.do files"' _n ///
    `"==============================================*/"' _n(2) ///
    `"clear all"' _n ///
    `"set more off"' _n ///
    `"set maxvar 32767"' _n ///
    `"set matsize 11000"' _n ///
    `"version 16"' _n(2) ///
    `"global base     "/Users/amalkova/Library/CloudStorage/OneDrive-FloridaInstituteofTechnology/Credit market (1)""' _n ///
    `"global welfare  "\$base/Welfare analysis""' _n ///
    `"global dodir    "\$welfare/Do files""' _n ///
    `"global dofiles  "\$welfare/Do files""' _n ///
    `"global data     "\$welfare/Data""' _n ///
    `"global results  "\$welfare/Results""' _n ///
    `"global tables   "\$welfare/Tables""' _n ///
    `"global figures  "\$welfare/Figures""' _n ///
    `"global logdir   "\$welfare/Logs""' _n ///
    `"global crdata   "\$base/Comparative Economics""' _n(2) ///
    `"* Combined long-format DTA files"' _n ///
    `"global ind_combined  "\$data/IND/RLMS_IND_1994_2023_eng_dta.dta""' _n ///
    `"global hh_combined   "\$data/HH/RLMS_HH_1994_2023_eng_dta.dta""' _n(2) ///
    `"capture mkdir "\$data""' _n ///
    `"capture mkdir "\$results""' _n ///
    `"capture mkdir "\$tables""' _n ///
    `"capture mkdir "\$figures""' _n ///
    `"capture mkdir "\$logdir""' _n

file close _globals

display as result _n "welfare_globals.do written to: ${dodir}/welfare_globals.do"

* ============================================================================ *
*   5.  VERIFY THAT COMBINED DTA FILES EXIST
* ============================================================================ *

display as result _n "--- Checking for combined data files ---" _n

local all_ok = 1

foreach f in ind_combined hh_combined {
    capture confirm file "${`f'}"
    if _rc == 0 {
        display as result "  FOUND : ${`f'}"
    }
    else {
        display as error "  MISSING : ${`f'}"
        local all_ok = 0
    }
}

if `all_ok' == 1 {
    display as result _n "All required data files are present."
}
else {
    display as error _n "WARNING: One or more data files are missing."
    display as error "Check that RAR files have been extracted to: ${data}/HH and ${data}/IND"
}

* ============================================================================ *
*   7.  QUICK DESCRIBE OF EACH DTA FILE
* ============================================================================ *

display as result _n(2) "=============================================="
display as result "  INDIVIDUAL file (combined, long format)"
display as result "  Expected: ~10 GB, person-year observations"
display as result "  Keys: idind (person), id_h (household), id_w (year)"
display as result "=============================================="

capture noisily {
    describe using "${ind_combined}", short
}

display as result _n(2) "=============================================="
display as result "  HOUSEHOLD file (combined, long format)"
display as result "  Expected: ~2.5 GB, 165,286 obs, 2,011 vars"
display as result "  Keys: id_h (household), id_w (year)"
display as result "=============================================="

capture noisily {
    describe using "${hh_combined}", short
}

* ============================================================================ *
*   8.  PRINT RLMS ROUND-TO-YEAR MAPPING
* ============================================================================ *

display as result _n(2) "=============================================="
display as result "  RLMS Round-to-Year Mapping"
display as result "=============================================="

display as result _n "  Round  3  ->  1994 (Jun-Jul)"
display as result "  Round  4  ->  1994 (Nov-Dec)"
display as result "  Round  5  ->  1995"
display as result "  Round  6  ->  1996"
display as result "  Round  7  ->  1998 (spring)"
display as result "  Round  8  ->  1998 (Oct-Dec)"
display as result "  Round  9  ->  2000"
display as result "  Round 10  ->  2001"
display as result "  Round 11  ->  2002"
display as result "  Round 12  ->  2003"
display as result "  Round 13  ->  2004"
display as result "  Round 14  ->  2005"
display as result "  Round 15  ->  2006"
display as result "  Round 16  ->  2007"
display as result "  Round 17  ->  2008"
display as result "  Round 18  ->  2009"
display as result "  Round 19  ->  2010"
display as result "  Round 20  ->  2011"
display as result "  Round 21  ->  2012"
display as result "  Round 22  ->  2013"
display as result "  Round 23  ->  2014"
display as result "  Round 24  ->  2015"
display as result "  Round 25  ->  2016"
display as result "  Round 26  ->  2017"
display as result "  Round 27  ->  2018"
display as result "  Round 28  ->  2019"
display as result "  Round 29  ->  2020"
display as result "  Round 30  ->  2021"
display as result "  Round 31  ->  2022"
display as result "  Round 32  ->  2023"

display as result _n "Note: id_w in both combined files encodes the survey year."
display as result "      No appending or reshaping is needed -- files are already"
display as result "      in long format (one obs per household-year or person-year)."

* ============================================================================ *
*   9.  QUICK CHECK OF KEY IDENTIFIERS
* ============================================================================ *

display as result _n(2) "=============================================="
display as result "  Key identifier check (IND file, first 100 obs)"
display as result "=============================================="

capture noisily {
    use idind id_h id_w using "${ind_combined}" in 1/100, clear
    describe, short
    list in 1/5, clean noobs
    display _n "Unique id_w values in first 100 obs:"
    tabulate id_w
}

display as result _n(2) "=============================================="
display as result "  Key identifier check (HH file, first 100 obs)"
display as result "=============================================="

capture noisily {
    use id_h id_w using "${hh_combined}" in 1/100, clear
    describe, short
    list in 1/5, clean noobs
    display _n "Unique id_w values in first 100 obs:"
    tabulate id_w
}

* ============================================================================ *
*   10.  WRAP UP
* ============================================================================ *

display as result _n(2) "=============================================="
display as result "  Step W0 complete."
display as result "  Next: run Step W1 - Build welfare analysis panel.do"
display as result "=============================================="

log close w0

* end of Step W0
