/*==============================================
  Welfare Analysis -- Global macros
  Auto-generated by Step W0
  Called by all Step W*.do files
==============================================*/

clear all
set more off
capture set maxvar 32767
capture set matsize 11000
capture version 15

global base     "/Users/amalkova/Library/CloudStorage/OneDrive-FloridaInstituteofTechnology/_Research/Credit_Market/Credit market (1)"
global welfare  "$base/Welfare analysis"
global dodir    "$welfare/Do files"
global dofiles  "$welfare/Do files"
global data     "$welfare/Data"
global results  "$welfare/Results"
global tables   "$welfare/Tables"
global figures  "$welfare/Figures"
global logdir   "$welfare/Logs"
global crdata   "$base/Comparative Economics"

* Combined long-format DTA files
global ind_combined  "$data/IND/RLMS_IND_1994_2023_eng_dta.dta"
global hh_combined   "$data/HH/RLMS_HH_1994_2023_eng_dta.dta"

capture mkdir "$data"
capture mkdir "$results"
capture mkdir "$tables"
capture mkdir "$figures"
capture mkdir "$logdir"
